name: Deploy Infrastructure with Terraform

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
        - 'terraform/**'

jobs:
  terraform-plan-and-apply:
    runs-on: ubuntu-latest

    env:
      AWS_REGION : ${{ secrets.AWS_REGION }}
    
    steps:
      - name: Checkout code 
        uses: actions/checkout@v3
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
          terraform_version: 1.13.0
      
      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform
      
      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file=environments/dev/terraform.tfvars
        working-directory: ./terraform
